name: Automated Tests Using Pabot

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      automation-directory: ${{ vars.CI_AUTOMATION_PROJECT_NAME }}

    defaults:
      run:
        working-directory: ${{ env.automation-directory }}

    services:
      selenium:
        image: selenium/standalone-firefox:latest
        options: --shm-size=2g

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Clone Automation Project
        working-directory: ${{ github.workspace }}
        run: git clone ${{ vars.CI_AUTOMATION_PROJECT_URL }}

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install robotframework-pabot==2.16.0

      - name: Run Automated Tests
        run: pabot --processes 2 --outputdir results --variable BROWSER:headlessfirefox tests

      - name: Save Test Report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Test Report
          path: ./${{ env.automation-directory }}/results
