name: Automated Tests Using Pabot

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-firefox:latest
        options: --shm-size=2g

    steps:
      - name: Checkout Repository at delorean-challenge-automation-e2e
        uses: actions/checkout@v2
        with:
          repository: eliezermenezes/delorean-challenge-automation-e2e

      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install robotframework-pabot==2.16.0

      - name: Run Automated Tests
        run: pabot --processes 2 --outputdir results --variable BROWSER:headlessfirefox tests

      - name: Save Test Report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Test Report
          path: results

      - name: Send Telegram Notification
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Status: ${{ job.status }}
            See Jobs: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          document: results/output.xml
