name: Automated Tests Together

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        options: --shm-size=2g

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Start Server
        run: npm start &

      # Caso queira fazer o build da aplicação e servir usando o "http-server", descomente os passos abaixo
      # - name: Build Application
      #   run: npm run build -- --configuration production

      # - name: Start Temporary Web Server
      #   run: npx http-server ./dist/delorean-challenge -p 4200 &

      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Clone Automation Project
        run: git clone ${{ vars.CI_AUTOMATION_PROJECT_URL }}

      - name: Install Dependencies
        working-directory: ${{ vars.CI_AUTOMATION_PROJECT_NAME }}
        run: pip install -r requirements.txt

      - name: Run Automated Tests
        working-directory: ${{ vars.CI_AUTOMATION_PROJECT_NAME }}
        run: robot -d results -v BROWSER:headlesschrome -v URL:http://localhost:4200 tests

      - name: Save Test Report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Test Report
          path: ./${{ vars.CI_AUTOMATION_PROJECT_NAME }}/results
